name: kege-station

services:
  postgres:
    container_name: kege-station-postgres
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DbConfiguration__User}
      POSTGRES_PASSWORD: ${DbConfiguration__Password}
      POSTGRES_DB: ${DbConfiguration__Database}
      PGUSER: ${DbConfiguration__User}
      PGDATABASE: ${DbConfiguration__Database}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DbConfiguration__User} -d ${DbConfiguration__Database}" ]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "6432:5432"
    volumes:
      - kege-station-postgres-data:/var/lib/postgresql
    networks:
      - kege-station-network
  
  kege-station.presentation:
    container_name: kege-station-app
    restart: unless-stopped
    env_file:
      - ./backend/example.env
    build:
      context: ./backend
      dockerfile: KEGEstation.Presentation/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kege-station-network
    depends_on:
      postgres:
        condition: service_healthy
      s3:
        condition: service_healthy
  
  frontend:
    container_name: kege-station-front
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api/v1/
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - kege-station-network
    depends_on:
      kege-station.presentation:
        condition: service_started
  
  s3:
    security_opt:
      - "no-new-privileges:true"
    image: rustfs/rustfs:latest
    container_name: rustfs-server
    ports:
      - "9000:9000" # S3 API port
      - "9001:9001" # Console port
    environment:
      - RUSTFS_VOLUMES=/data/rustfs{0..3} # Define 4 storage volumes
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_ACCESS_KEY=admin
      - RUSTFS_SECRET_KEY=adminpass
      - RUSTFS_OBS_LOGGER_LEVEL=info
    volumes:
      - rustfs-data:/data
      - rustfs-logs:/app/logs
    networks:
      - kege-station-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "sh", "-c",
          "curl -f http://127.0.0.1:9000/health && curl -f http://127.0.0.1:9001/rustfs/console/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rustfs-data:
  rustfs-logs:
  kege-station-postgres-data:

networks:
  kege-station-network:
    driver: bridge