name: kege-station

services:
  postgres-db:
    container_name: kege-station-postgres
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DbConfiguration__User}
      POSTGRES_PASSWORD: ${DbConfiguration__Password}
      POSTGRES_DB: ${DbConfiguration__Database}
      PGUSER: ${DbConfiguration__User}
      PGDATABASE: ${DbConfiguration__Database}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DbConfiguration__User} -d ${DbConfiguration__Database}" ]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "6432:5432"
    volumes:
      - kege-station-postgres-data:/var/lib/postgresql
    networks:
      - kege-station-network
  
  kege-station.presentation:
    container_name: kege-station-app
    restart: unless-stopped
    env_file:
      - ./backend/example.env
    build:
      context: ./backend
      dockerfile: KEGEstation.Presentation/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kege-station-network
    depends_on:
      postgres-db:
        condition: service_healthy
      s3:
        condition: service_healthy

  s3:
    image: minio/minio:latest
    container_name: kege-station-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpass
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio-data:/data
    networks:
      - kege-station-network

volumes:
  minio-data:
  kege-station-postgres-data:

networks:
  kege-station-network:
    driver: bridge